/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jhonatar' at '30/07/16 00:37' with Gradle 2.14
 *
 * @author jhonatar, @date 30/07/16 00:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
